use crate::cpu::instruction::Instruction;
use crate::cpu::instruction::AddressingMode::*;

pub fn parse_instruction(opcode:u8) -> Instruction {
    match opcode {
        0x00 => Instruction::new(opcode, "BRK", Implied, true),
        0x02 => Instruction::new(opcode, "HTL", Implied, false),
        0x05 => Instruction::new(opcode, "ORA", ZeroPage, false),
        0x06 => Instruction::new(opcode, "ASL", ZeroPage, true),
        0x08 => Instruction::new(opcode, "PHP", Implied, false),
        0x09 => Instruction::new(opcode, "ORA", Immediate, false),
        0x0A => Instruction::new(opcode, "ASL", Implied, false),
        0x0D => Instruction::new(opcode, "ORA", Absolute, false),
        0x0E => Instruction::new(opcode, "ASL", Absolute, true),
        0x10 => Instruction::new(opcode, "BPL", Relative, false),
        0x18 => Instruction::new(opcode, "CLC", Implied, false),
        0x20 => Instruction::new(opcode, "JSR", Absolute, true),
        0x24 => Instruction::new(opcode, "BIT", ZeroPage, false),
        0x25 => Instruction::new(opcode, "AND", ZeroPage, false),
        0x26 => Instruction::new(opcode, "ROL", ZeroPage, false),
        0x28 => Instruction::new(opcode, "PLP", Implied, false),
        0x29 => Instruction::new(opcode, "AND", Immediate, false),
        0x2A => Instruction::new(opcode, "ROL", Implied, false),
        0x2C => Instruction::new(opcode, "BIT", Absolute, false),
        0x2D => Instruction::new(opcode, "AND", Absolute, false),
        0x2E => Instruction::new(opcode, "ROL", Absolute, false),
        0x30 => Instruction::new(opcode, "BMI", Relative, false),
        0x38 => Instruction::new(opcode, "SEC", Implied, false),
        0x40 => Instruction::new(opcode, "RTI", Implied, true),
        0x45 => Instruction::new(opcode, "EOR", ZeroPage, false),
        0x46 => Instruction::new(opcode, "LSR", ZeroPage, false),
        0x48 => Instruction::new(opcode, "PHA", Implied, true),
        0x49 => Instruction::new(opcode, "EOR", Immediate, false),
        0x4A => Instruction::new(opcode, "LSR", Implied, false),
        0x4C => Instruction::new(opcode, "JMP", Absolute, false),
        0x4D => Instruction::new(opcode, "EOR", Absolute, false),
        0x4E => Instruction::new(opcode, "LSR", Absolute, false),
        0x50 => Instruction::new(opcode, "BVC", Relative, false),
        0x58 => Instruction::new(opcode, "CLI", Implied, false),
        0x60 => Instruction::new(opcode, "RTS", Implied, true),
        0x65 => Instruction::new(opcode, "ADC", ZeroPage, false),
        0x66 => Instruction::new(opcode, "ROR", ZeroPage, false),
        0x68 => Instruction::new(opcode, "PLA", Implied, false),
        0x69 => Instruction::new(opcode, "ADC", Immediate, true),
        0x6A => Instruction::new(opcode, "ROR", Implied, false),
        0x6D => Instruction::new(opcode, "ADC", Absolute, false),
        0x6E => Instruction::new(opcode, "ROR", Absolute, false),
        0x70 => Instruction::new(opcode, "BVS", Relative, false),
        0x78 => Instruction::new(opcode, "SEI", Implied, false),
        0x84 => Instruction::new(opcode, "STY", ZeroPage, true),
        0x85 => Instruction::new(opcode, "STA", ZeroPage, true),
        0x86 => Instruction::new(opcode, "STX", ZeroPage, true),
        0x88 => Instruction::new(opcode, "DEY", Implied, false),
        0x8A => Instruction::new(opcode, "TXA", Implied, false),
        0x8C => Instruction::new(opcode, "STY", ZeroPage, true),
        0x8D => Instruction::new(opcode, "STA", Absolute, true),
        0x8E => Instruction::new(opcode, "STX", Absolute, true),
        0x90 => Instruction::new(opcode, "BCC", Relative, true),
        0x98 => Instruction::new(opcode, "TYA", Implied, false),
        0x9A => Instruction::new(opcode, "TXS", Implied, false),
        0xA0 => Instruction::new(opcode, "LDY", Immediate, false),
        0xA2 => Instruction::new(opcode, "LDX", Immediate, false),
        0xA5 => Instruction::new(opcode, "LDA", ZeroPage, false),
        0xA8 => Instruction::new(opcode, "TAY", Implied, false),
        0xA9 => Instruction::new(opcode, "LDA", Immediate, false),
        0xAA => Instruction::new(opcode, "TAX", Implied, false),
        0xAD => Instruction::new(opcode, "LDA", Absolute, false),
        0xB0 => Instruction::new(opcode, "BCS", Relative, false),
        0xB8 => Instruction::new(opcode, "CLV", Implied, false),
        0xBA => Instruction::new(opcode, "TSX", Implied, false),
        0xC5 => Instruction::new(opcode, "CMP", ZeroPage, false),
        0xC6 => Instruction::new(opcode, "DEC", ZeroPage, true),
        0xC8 => Instruction::new(opcode, "INY", Implied, false),
        0xC9 => Instruction::new(opcode, "CMP", Immediate, false),
        0xCA => Instruction::new(opcode, "DEX", Implied, false),
        0xCD => Instruction::new(opcode, "CMP", Absolute, false),
        0xCE => Instruction::new(opcode, "DEC", Absolute, true),
        0xD0 => Instruction::new(opcode, "BNE", Relative, false),
        0xD8 => Instruction::new(opcode, "CLD", Implied, false),
        0xE5 => Instruction::new(opcode, "SBC", ZeroPage, false),
        0xE7 => Instruction::new(opcode, "INC", ZeroPage, true),
        0xE8 => Instruction::new(opcode, "INX", Implied, false),
        0xE9 => Instruction::new(opcode, "SBC", Immediate, false),
        0xEE => Instruction::new(opcode, "INC", Absolute, true),
        0xEA => Instruction::new(opcode, "NOP", Implied, false),
        0xED => Instruction::new(opcode, "SBC", Absolute, false),
        0xF0 => Instruction::new(opcode, "BEQ", Relative, false),
        0xF8 => Instruction::new(opcode, "SED", Implied, false),

        _ => {
            println!("Unknown instruction opcode: {:X}", opcode);
            Instruction::new(opcode, "HTL", Implied, false)
        }
    }
}